#!/bin/bash

install_issue(){
  echo "Install IP-issue-screen..."
  rm -f /usr/local/bin/get-ip-address
  cp issue-screen/get-ip-address /usr/local/bin/get-ip-address
  chmod +x /usr/local/bin/get-ip-address
  
  rm -f /usr/local/bin/refresh-issue
  cp issue-screen/refresh-issue /usr/local/bin/refresh-issue
  chmod +x /usr/local/bin/refresh-issue
  
  mv /etc/issue /etc/issue-standard
  /usr/local/bin/refresh-issue
  (crontab -u root -l ; echo "@reboot /usr/local/bin/refresh-issue") | crontab -u root -
  echo "Finished"
}

install_motd(){
  echo "Install motd-screen"
  apt -y install figlet python-apt
  rm -f /etc/update-motd.d/*
  truncate -s 0 /etc/motd
  cp -R motd-screen/* /etc/update-motd.d/
  chmod -R +x /etc/update-motd.d/
  for f in /etc/update-motd.d/*; do $f; done
  echo "Look for these lines and mach them:"
  echo "PrintMotd no"
  echo "PrintLastLog yes"
  echo "#Banner /etc/issue"
  read -p "Press enter to continue"
  nano /etc/ssh/sshd_config
  service ssh reload
  (crontab -u root -l ; echo "@reboot /usr/bin/apt-get update") | crontab -u root -
  echo "Finished"
}

auto_edit_bashrc(){
  cp templates/.bashrc ~/.bashrc
  . ~/.bashrc
  echo "Finished"
}

promt_install(){
  while true; do
    read -p "$1 (y/n)" yn
    case $yn in
        [Yy]* ) shift; eval $@ ; break;;
        [Nn]* ) break;;
        * ) echo "Please answer yes or no.";;
    esac
  done
  echo
}

apt_install(){
  promt_install "Do you wish to install '$@'?" apt -y install $@
}

promt_install "Do you wish to install the IP-issue-screen?" install_issue
promt_install "Do you wish to install the dynamic login motd?" install_motd
promt_install "Do you wish to auto edit .bashrc?" auto_edit_bashrc
apt_install htop nload iotop curl atop iftop tree
apt_install glances
apt_install open-vm-tools
apt_install net-tools


