#!/bin/bash

install_issue(){
  echo "Install IP-issue-screen..."
  rm -f /usr/local/bin/get-ip-address
  cp issue-screen/get-ip-address /usr/local/bin/get-ip-address
  chmod +x /usr/local/bin/get-ip-address
  
  rm -f /etc/network/if-up.d/show-ip-address
  cp issue-screen/show-ip-address /usr/local/bin/show-ip-address
  chmod +x /usr/local/bin/show-ip-address
  
  mv /etc/issue /etc/issue-standard
  /usr/local/bin/show-ip-address
  echo "Finished"
}

install_motd(){
  echo "Install motd-screen"
  apt -y install figlet python-apt
  rm -f /etc/update-motd.d/10-uname
  truncate -s 0 /etc/motd
  cp -R motd-screen/* /etc/update-motd.d/
  chmod -R +x /etc/update-motd.d/
  for f in /etc/update-motd.d/*; do $f; done
  echo "Look for these lines and mach them:"
  echo "PrintMotd no"
  echo "PrintLastLog yes"
  echo "#Banner /etc/issue"
  read -p "Press enter to continue"
  nano /etc/ssh/sshd_config
  service ssh reload
  echo "Finished"
}

auto_edit_bashrc(){
  cp templates/.bashrc ~/.bashrc
  . ~/.bashrc
  echo "Finished"
}

promt_install(){
  while true; do
    read -p "$1 (y/n)" yn
    case $yn in
        [Yy]* ) shift; eval $@ ; break;;
        [Nn]* ) break;;
        * ) echo "Please answer yes or no.";;
    esac
  done
  echo
}

promt_install "Do you wish to install the IP-issue-screen?" install_issue
promt_install "Do you wish to install the dynamic login motd?" install_motd
promt_install "Do you wish to install these programs (htop nload iotop curl atop iftop)?" apt -y install htop nload iotop curl atop iftop
promt_install "Do you wish to install glances?" apt -y install glances
promt_install "Do you wish to auto edit .bashrc?" auto_edit_bashrc
promt_install "Do you wish to install open-vm-tools?" apt -y install open-vm-tools


